//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.BahriaUniversity.edu.pk/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.BahriaUniversity.edu.pk/", ConfigurationName="ServiceReference1.MyServiceSoap")]
    public interface MyServiceSoap {
        
        // CODEGEN: Generating message contract since element name input from namespace http://www.BahriaUniversity.edu.pk/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BahriaUniversity.edu.pk/GetData", ReplyAction="*")]
        Test.ServiceReference1.GetDataResponse GetData(Test.ServiceReference1.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.BahriaUniversity.edu.pk/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.ServiceReference1.GetDataResponse> GetDataAsync(Test.ServiceReference1.GetDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://www.BahriaUniversity.edu.pk/", Order=0)]
        public Test.ServiceReference1.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(Test.ServiceReference1.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.BahriaUniversity.edu.pk/")]
    public partial class GetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public GetDataRequestBody() {
        }
        
        public GetDataRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://www.BahriaUniversity.edu.pk/", Order=0)]
        public Test.ServiceReference1.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(Test.ServiceReference1.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.BahriaUniversity.edu.pk/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Test.ServiceReference1.ArrayOfString[] GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(Test.ServiceReference1.ArrayOfString[] GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServiceSoapChannel : Test.ServiceReference1.MyServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceSoapClient : System.ServiceModel.ClientBase<Test.ServiceReference1.MyServiceSoap>, Test.ServiceReference1.MyServiceSoap {
        
        public MyServiceSoapClient() {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference1.GetDataResponse Test.ServiceReference1.MyServiceSoap.GetData(Test.ServiceReference1.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public Test.ServiceReference1.ArrayOfString[] GetData(string input) {
            Test.ServiceReference1.GetDataRequest inValue = new Test.ServiceReference1.GetDataRequest();
            inValue.Body = new Test.ServiceReference1.GetDataRequestBody();
            inValue.Body.input = input;
            Test.ServiceReference1.GetDataResponse retVal = ((Test.ServiceReference1.MyServiceSoap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.ServiceReference1.GetDataResponse> Test.ServiceReference1.MyServiceSoap.GetDataAsync(Test.ServiceReference1.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference1.GetDataResponse> GetDataAsync(string input) {
            Test.ServiceReference1.GetDataRequest inValue = new Test.ServiceReference1.GetDataRequest();
            inValue.Body = new Test.ServiceReference1.GetDataRequestBody();
            inValue.Body.input = input;
            return ((Test.ServiceReference1.MyServiceSoap)(this)).GetDataAsync(inValue);
        }
    }
}
